### ISSUE TITLE
Export as CSV

### ISSUE THREAD

**Issue by bryantgeorge** [senior-knights/course-schedulizer#20]
Maybe have this branch export as well? (If it's not too complex)

**Comment by Jdellis818** [comment]
@Syobnaf I'd like to note that I made a slight change to the interface that may affect this process. Rather than having the section be the parent element, I switched it to be the Course so that we don't have to keep duplicating course data for every new section that is created. I updated the import function accordingly, but it may require a slight change in exporting as well. #22 contains the changes.

**Comment by bryantgeorge** [comment]
Awesome, thanks for the heads up!
